#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE $USERS_DATABASE;
  GRANT ALL PRIVILEGES ON DATABASE $USERS_DATABASE TO $POSTGRES_USER;

  \connect $USERS_DATABASE $POSTGRES_USER
  CREATE EXTENSION IF NOT EXISTS citext;
  CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
  \q
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE $AUTH_DATABASE;
  GRANT ALL PRIVILEGES ON DATABASE $AUTH_DATABASE TO $POSTGRES_USER;

  \connect $AUTH_DATABASE $POSTGRES_USER
  CREATE EXTENSION IF NOT EXISTS citext;
  CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
  \q
EOSQL
